version: '3.8'

services:
  web:
    build: .
    ports:
      - "7000:7000"
    environment:
      FLASK_ENV: ${FLASK_ENV:-development}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      SECRET_KEY: ${SECRET_KEY}
